"""Features package for quant research - unified interface to all feature modules."""
from __future__ import annotations

from quant.features.microstructure import (
    amihud_illiquidity,
    bid_ask_spread,
    kyle_lambda,
    order_flow_imbalance,
    relative_spread,
    roll_measure,
    time_weighted_average_price,
    volume_change,
    volume_moving_average,
    volume_profile,
    volume_weighted_average_price,
    volume_z_score,
)
from quant.features.statistical import (
    ewm_std,
    ewma,
    percent_rank,
    rolling_beta,
    rolling_corr,
    rolling_cov,
    rolling_kurt,
    rolling_mean,
    rolling_quantile,
    rolling_skew,
    rolling_std,
    z_score,
)
from quant.features.technical import (
    atr,
    bollinger_bands,
    breakout_levels,
    ema,
    log_returns,
    macd,
    momentum,
    moving_average_distance,
    rolling_returns,
    rsi,
    simple_returns,
    sma,
)
from quant.features.volatility import (
    atr_volatility,
    ewma_volatility,
    garman_klass_volatility,
    parkinson_volatility,
    realized_volatility,
    rogers_satchell_volatility,
    rolling_volatility,
    volatility_cone,
)

__all__ = [
    # Returns
    "simple_returns",
    "log_returns",
    "rolling_returns",
    # Trend
    "sma",
    "ema",
    "moving_average_distance",
    "momentum",
    "breakout_levels",
    "macd",
    # Mean Reversion
    "rsi",
    "bollinger_bands",
    # Volatility
    "atr",
    "realized_volatility",
    "rolling_volatility",
    "ewma_volatility",
    "garman_klass_volatility",
    "parkinson_volatility",
    "rogers_satchell_volatility",
    "atr_volatility",
    "volatility_cone",
    # Statistical
    "z_score",
    "rolling_mean",
    "rolling_std",
    "rolling_skew",
    "rolling_kurt",
    "rolling_corr",
    "rolling_cov",
    "rolling_beta",
    "rolling_quantile",
    "percent_rank",
    "ewma",
    "ewm_std",
    # Microstructure
    "bid_ask_spread",
    "relative_spread",
    "volume_weighted_average_price",
    "time_weighted_average_price",
    "volume_profile",
    "kyle_lambda",
    "amihud_illiquidity",
    "roll_measure",
    "order_flow_imbalance",
    "volume_change",
    "volume_z_score",
    "volume_moving_average",
]
