"""ML package for machine learning in quant research."""
from quant.ml.cv import (
    CVResult,
    CVSummary,
    TimeSeriesCV,
    TimeSeriesCVConfig,
    combinatorial_purged_cv,
    cross_validate,
    evaluate_model,
    purged_kfold_cv,
    walk_forward_predict,
)
from quant.ml.features import (
    FeatureConfig,
    FeaturePipeline,
    create_default_pipeline,
    create_minimal_pipeline,
)
from quant.ml.models import (
    CLASSIFICATION_MODELS,
    REGRESSION_MODELS,
    BaseMLModel,
    ElasticNetModel,
    ExtraTreesClsModel,
    ExtraTreesRegModel,
    GradientBoostingClsModel,
    GradientBoostingRegModel,
    HistGradientBoostingClsModel,
    HistGradientBoostingRegModel,
    KNNClsModel,
    KNNRegModel,
    LassoModel,
    LinearRegressionModel,
    LogisticRegressionModel,
    MLPClsModel,
    MLPRegModel,
    ModelConfig,
    RandomForestClsModel,
    RandomForestRegModel,
    RidgeClassifierModel,
    RidgeModel,
    SVCModel,
    SVRModel,
    create_model,
    ensemble_predict,
    get_model_class,
    stack_models,
    tune_hyperparameters,
)
from quant.ml.online import (
    DriftDetector,
    OnlineConfig,
    OnlineEnsemble,
    OnlineLearner,
    RollingRetrainer,
)
from quant.ml.pipeline import (
    MLPipeline,
    MLPipelineConfig,
    MLPipelineResult,
    compare_models,
    run_ml_experiment,
    walk_forward_backtest,
)

__all__ = [
    # Features
    "FeatureConfig",
    "FeaturePipeline",
    "create_default_pipeline",
    "create_minimal_pipeline",

    # Cross-validation
    "TimeSeriesCVConfig",
    "TimeSeriesCV",
    "CVResult",
    "CVSummary",
    "cross_validate",
    "evaluate_model",
    "walk_forward_predict",
    "purged_kfold_cv",
    "combinatorial_purged_cv",

    # Models
    "ModelConfig",
    "BaseMLModel",
    "create_model",
    "get_model_class",
    "tune_hyperparameters",
    "ensemble_predict",
    "stack_models",
    "REGRESSION_MODELS",
    "CLASSIFICATION_MODELS",

    # Specific models
    "LinearRegressionModel",
    "RidgeModel",
    "LassoModel",
    "ElasticNetModel",
    "RandomForestRegModel",
    "GradientBoostingRegModel",
    "ExtraTreesRegModel",
    "HistGradientBoostingRegModel",
    "SVRModel",
    "KNNRegModel",
    "MLPRegModel",
    "LogisticRegressionModel",
    "RidgeClassifierModel",
    "RandomForestClsModel",
    "GradientBoostingClsModel",
    "ExtraTreesClsModel",
    "HistGradientBoostingClsModel",
    "SVCModel",
    "KNNClsModel",
    "MLPClsModel",

    # Online learning
    "OnlineConfig",
    "OnlineLearner",
    "RollingRetrainer",
    "DriftDetector",
    "OnlineEnsemble",

    # Pipeline
    "MLPipelineConfig",
    "MLPipelineResult",
    "MLPipeline",
    "run_ml_experiment",
    "compare_models",
    "walk_forward_backtest",
]
