"""Production infrastructure for quant platform."""
from quant.production.alerts import (
    Alert,
    AlertLevel,
    AlertManager,
    AlertRule,
    AlertStatus,
    check_metric_threshold,
    create_default_rules,
    email_handler,
    get_alert_manager,
    log_handler,
    webhook_handler,
)
from quant.production.api import (
    BacktestRequest,
    BacktestResponse,
    DataDownloadRequest,
    HealthResponse,
    MLExperimentRequest,
    MLExperimentResponse,
    create_app,
    run_server,
)
from quant.production.config import (
    APIConfig,
    DatabaseConfig,
    MonitoringConfig,
    ProductionConfig,
    RedisConfig,
    SchedulerConfig,
    SecurityConfig,
    StorageConfig,
    get_config,
    load_config_from_env,
    load_config_from_file,
    reset_config_cache,
)
from quant.production.monitoring import (
    ACTIVE_CONNECTIONS,
    BACKTEST_DURATION,
    BACKTEST_RUNS,
    DATA_DOWNLOADS,
    ERROR_COUNT,
    ML_TRAINING_DURATION,
    ML_TRAINING_RUNS,
    REQUEST_COUNT,
    REQUEST_LATENCY,
    HealthCheck,
    MetricsCollector,
    StructuredLogger,
    configure_logging,
    get_health_check,
    get_logger,
    get_metrics_collector,
    log_context,
    log_execution_time,
    log_execution_time_async,
)
from quant.production.scheduler import (
    JobInfo,
    JobScheduler,
    cleanup_old_data,
    daily_backtest,
    daily_data_update,
    get_scheduler,
    health_check_job,
    setup_default_jobs,
    weekly_model_retrain,
)

__all__ = [
    # Config
    "ProductionConfig",
    "DatabaseConfig",
    "RedisConfig",
    "APIConfig",
    "MonitoringConfig",
    "SchedulerConfig",
    "StorageConfig",
    "SecurityConfig",
    "get_config",
    "load_config_from_env",
    "load_config_from_file",
    "reset_config_cache",

    # Monitoring
    "configure_logging",
    "get_logger",
    "get_metrics_collector",
    "get_health_check",
    "StructuredLogger",
    "MetricsCollector",
    "HealthCheck",
    "log_context",
    "log_execution_time",
    "log_execution_time_async",
    "REQUEST_COUNT",
    "REQUEST_LATENCY",
    "ACTIVE_CONNECTIONS",
    "BACKTEST_RUNS",
    "BACKTEST_DURATION",
    "ML_TRAINING_RUNS",
    "ML_TRAINING_DURATION",
    "DATA_DOWNLOADS",
    "ERROR_COUNT",

    # API
    "create_app",
    "run_server",
    "BacktestRequest",
    "BacktestResponse",
    "MLExperimentRequest",
    "MLExperimentResponse",
    "DataDownloadRequest",
    "HealthResponse",

    # Scheduler
    "JobScheduler",
    "JobInfo",
    "get_scheduler",
    "setup_default_jobs",
    "daily_data_update",
    "weekly_model_retrain",
    "daily_backtest",
    "cleanup_old_data",
    "health_check_job",

    # Alerts
    "AlertManager",
    "Alert",
    "AlertRule",
    "AlertLevel",
    "AlertStatus",
    "get_alert_manager",
    "create_default_rules",
    "log_handler",
    "webhook_handler",
    "email_handler",
    "check_metric_threshold",
]
